spring:
  application:
    name: testtgbot
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase :
    change-log : db/changelog/main-changelog.xml
bot:
  name: Lernjbot
  key: 6244771295:AAEYHhKvgoKgvU2i--iw5GHu_eFNYygnVqo
  owner: 5118893958

cron:
  scheduler: '0 15 * * * *'